name: Generate r3d.c3l Artifact

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        type: string

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder"
